### ISSUE TITLE
Consider publishing a MacOS App Bundle

### ISSUE THREAD

**Issue by slynn1324** [Phoenix09/filebot#2]
Rookie here -- but it seems as if these 2 commands will wrap the jar file into a working .app bundle with Java 9 and Mac OS 10.13.  Only downside (other than more work) is that the Java .app files are pretty large on MacOS as they bundle the necessary JRE.   Note - javapackager comes with JDK8+, and hdiutil is MacOS native.

```
# create the .app file
javapackager -deploy -BappVersion=4.7.19 -Bicon=filebot.icns -native image -srcdir . -srcfiles FileBot.jar -appclass net.filebot.Main -name FileBot -outdir dist -outfile FileBot.app -nosign -title FileBot -v

# create a dmg
hdiutil create -volname FileBot -srcfolder ./dist FileBot.dmg
```

**Comment by Phoenix09** [comment]
Added (without bundled JRE).
